// Textos de los reportes (PDF y Excel se arman en la API, en el idioma que pide el usuario).

export const REPORT_LOCALES = ['es', 'en', 'pt'] as const;
export type ReportLocale = (typeof REPORT_LOCALES)[number];

const es = {
  generatedBy: 'Generado con Shaddai el {date}',
  page: 'Página {page} de {pages}',
  period: 'Del {from} al {to}',
  asOf: 'Al {date}',
  currency: 'Moneda',
  total: 'Total',
  amount: 'Monto',
  date: 'Fecha',
  category: 'Categoría',
  account: 'Caja',
  description: 'Descripción',
  method: 'Medio de pago',
  reference: 'Referencia',
  person: 'Persona',
  document: 'Documento',
  count: 'Aportes',
  month: 'Mes',
  empty: 'Sin movimientos en el período.',
  incomeStatement: {
    title: 'Estado de resultados',
    file: 'estado-de-resultados',
    income: 'Ingresos',
    expense: 'Egresos',
    totalIncome: 'Total de ingresos',
    totalExpense: 'Total de egresos',
    net: 'Resultado',
  },
  balances: {
    title: 'Saldos de cajas',
    file: 'saldos-de-cajas',
    type: 'Tipo',
    balance: 'Saldo',
    inactive: '(inactiva)',
  },
  trend: {
    title: 'Evolución mensual',
    file: 'evolucion-mensual',
    tithe: 'Diezmos',
    offering: 'Ofrendas',
    otherIncome: 'Otros ingresos',
    expense: 'Egresos',
    net: 'Resultado',
  },
  contributions: {
    title: 'Aportes por persona',
    file: 'aportes-por-persona',
    tithe: 'Diezmos',
    other: 'Otros aportes',
  },
  certificate: {
    title: 'Constancia de aportes',
    file: 'constancia-de-aportes',
    body: 'Se deja constancia de que {name}{document} realizó durante el año {year} los aportes que se detallan a continuación a {church}.',
    documentPrefix: ', {document},',
    signature: 'Firma y aclaración',
    issuedAt: 'Emitida el {date}.',
  },
  receipt: {
    title: 'Recibo',
    file: 'recibo',
    number: 'N.º {number}',
    receivedFrom: 'Recibimos de',
    anonymous: 'Aporte anónimo',
    concept: 'En concepto de',
    signature: 'Firma',
  },
  accountTypes: { cash: 'Efectivo', bank: 'Banco', wallet: 'Billetera virtual' },
  methods: {
    cash: 'Efectivo',
    transfer: 'Transferencia',
    card: 'Tarjeta',
    wallet: 'Billetera virtual',
    other: 'Otro',
  },
  categories: {
    tithe: 'Diezmos',
    offering: 'Ofrendas',
    special_offering: 'Ofrendas especiales',
    donation: 'Donaciones',
    other_income: 'Otros ingresos',
    rent: 'Alquiler',
    utilities: 'Servicios (luz, agua, gas, internet)',
    maintenance: 'Mantenimiento',
    salaries: 'Sueldos y honorarios',
    missions: 'Misiones',
    social_aid: 'Ayuda social',
    supplies: 'Materiales y equipos',
    events: 'Eventos',
    other_expense: 'Otros egresos',
  } as Record<string, string>,
};

export type ReportLabels = typeof es;

const en: ReportLabels = {
  generatedBy: 'Generated with Shaddai on {date}',
  page: 'Page {page} of {pages}',
  period: 'From {from} to {to}',
  asOf: 'As of {date}',
  currency: 'Currency',
  total: 'Total',
  amount: 'Amount',
  date: 'Date',
  category: 'Category',
  account: 'Account',
  description: 'Description',
  method: 'Payment method',
  reference: 'Reference',
  person: 'Person',
  document: 'ID',
  count: 'Contributions',
  month: 'Month',
  empty: 'No transactions in the period.',
  incomeStatement: {
    title: 'Income statement',
    file: 'income-statement',
    income: 'Income',
    expense: 'Expenses',
    totalIncome: 'Total income',
    totalExpense: 'Total expenses',
    net: 'Net result',
  },
  balances: {
    title: 'Account balances',
    file: 'account-balances',
    type: 'Type',
    balance: 'Balance',
    inactive: '(inactive)',
  },
  trend: {
    title: 'Monthly trend',
    file: 'monthly-trend',
    tithe: 'Tithes',
    offering: 'Offerings',
    otherIncome: 'Other income',
    expense: 'Expenses',
    net: 'Net result',
  },
  contributions: {
    title: 'Contributions by person',
    file: 'contributions-by-person',
    tithe: 'Tithes',
    other: 'Other contributions',
  },
  certificate: {
    title: 'Contribution statement',
    file: 'contribution-statement',
    body: 'This certifies that {name}{document} made the following contributions to {church} during {year}.',
    documentPrefix: ' (ID {document})',
    signature: 'Signature and name',
    issuedAt: 'Issued on {date}.',
  },
  receipt: {
    title: 'Receipt',
    file: 'receipt',
    number: 'No. {number}',
    receivedFrom: 'Received from',
    anonymous: 'Anonymous contribution',
    concept: 'For',
    signature: 'Signature',
  },
  accountTypes: { cash: 'Cash', bank: 'Bank', wallet: 'Digital wallet' },
  methods: { cash: 'Cash', transfer: 'Transfer', card: 'Card', wallet: 'Digital wallet', other: 'Other' },
  categories: {
    tithe: 'Tithes',
    offering: 'Offerings',
    special_offering: 'Special offerings',
    donation: 'Donations',
    other_income: 'Other income',
    rent: 'Rent',
    utilities: 'Utilities',
    maintenance: 'Maintenance',
    salaries: 'Salaries and fees',
    missions: 'Missions',
    social_aid: 'Social aid',
    supplies: 'Supplies and equipment',
    events: 'Events',
    other_expense: 'Other expenses',
  },
};

const pt: ReportLabels = {
  generatedBy: 'Gerado com Shaddai em {date}',
  page: 'Página {page} de {pages}',
  period: 'De {from} a {to}',
  asOf: 'Em {date}',
  currency: 'Moeda',
  total: 'Total',
  amount: 'Valor',
  date: 'Data',
  category: 'Categoria',
  account: 'Caixa',
  description: 'Descrição',
  method: 'Forma de pagamento',
  reference: 'Referência',
  person: 'Pessoa',
  document: 'Documento',
  count: 'Contribuições',
  month: 'Mês',
  empty: 'Sem movimentos no período.',
  incomeStatement: {
    title: 'Demonstração de resultados',
    file: 'demonstracao-de-resultados',
    income: 'Entradas',
    expense: 'Saídas',
    totalIncome: 'Total de entradas',
    totalExpense: 'Total de saídas',
    net: 'Resultado',
  },
  balances: {
    title: 'Saldos dos caixas',
    file: 'saldos-dos-caixas',
    type: 'Tipo',
    balance: 'Saldo',
    inactive: '(inativo)',
  },
  trend: {
    title: 'Evolução mensal',
    file: 'evolucao-mensal',
    tithe: 'Dízimos',
    offering: 'Ofertas',
    otherIncome: 'Outras entradas',
    expense: 'Saídas',
    net: 'Resultado',
  },
  contributions: {
    title: 'Contribuições por pessoa',
    file: 'contribuicoes-por-pessoa',
    tithe: 'Dízimos',
    other: 'Outras contribuições',
  },
  certificate: {
    title: 'Declaração de contribuições',
    file: 'declaracao-de-contribuicoes',
    body: 'Declaramos que {name}{document} realizou durante o ano de {year} as contribuições detalhadas a seguir a {church}.',
    documentPrefix: ', {document},',
    signature: 'Assinatura e nome',
    issuedAt: 'Emitida em {date}.',
  },
  receipt: {
    title: 'Recibo',
    file: 'recibo',
    number: 'N.º {number}',
    receivedFrom: 'Recebemos de',
    anonymous: 'Contribuição anônima',
    concept: 'Referente a',
    signature: 'Assinatura',
  },
  accountTypes: { cash: 'Dinheiro', bank: 'Banco', wallet: 'Carteira digital' },
  methods: {
    cash: 'Dinheiro',
    transfer: 'Transferência',
    card: 'Cartão',
    wallet: 'Carteira digital',
    other: 'Outro',
  },
  categories: {
    tithe: 'Dízimos',
    offering: 'Ofertas',
    special_offering: 'Ofertas especiais',
    donation: 'Doações',
    other_income: 'Outras entradas',
    rent: 'Aluguel',
    utilities: 'Contas (luz, água, gás, internet)',
    maintenance: 'Manutenção',
    salaries: 'Salários e honorários',
    missions: 'Missões',
    social_aid: 'Ajuda social',
    supplies: 'Materiais e equipamentos',
    events: 'Eventos',
    other_expense: 'Outras saídas',
  },
};

export const LABELS: Record<ReportLocale, ReportLabels> = { es, en, pt };

/** Reemplaza {clave} por su valor. */
export const fill = (text: string, values: Record<string, string | number>) =>
  text.replace(/\{(\w+)\}/g, (_, k: string) => String(values[k] ?? ''));

/** Nombre de una categoría: el de la iglesia o el traducido por systemKey. */
export const categoryName = (
  l: ReportLabels,
  c: { name: string | null; systemKey: string | null } | null | undefined,
) => (c ? (c.name ?? (c.systemKey ? (l.categories[c.systemKey] ?? c.systemKey) : '')) : '');
